name = "webservices"
main = "src/worker.js"
compatibility_date = "2026-09-19"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_API_URL = "http://localhost:8787"
ADMIN_EMAIL="aryaniagencies@gmail.com"
ADMIN_EMAIL_PASS= "xxgpaagpxx"

[observability]
enabled = true